```{r}
required_packages <- c("tidyverse", "data.table", "here", "googledrive")

for (pkg in required_packages) {
	if (!requireNamespace(pkg, quietly = TRUE)) {
		suppressMessages(install.packages(pkg))
	}
}
#load all the dependencies
invisible(lapply(required_packages, function(pkg) {
	suppressPackageStartupMessages(library(pkg, character.only = TRUE))
}))

```

```{r}
folder_id <- "1oRNbZpA4kXZRsvcNe5K1FRYFKqqT5W2h"	#folder id
googledrive::drive_deauth()
folder <- drive_ls(as_id(folder_id))
filename <- "reviews_sampled.rds"
file_id <- folder[folder$name==filename] %>% pull(id) %>% as.character()
drive_download(as_id(file_id), path = here("data", "training_data",filename), overwrite = TRUE)

reviews_sampled <- readRDS(here("data", "training_data", filename))
```

####WARNING
Make sure the to include a downloaded "business.rds" in your local folder "raw_data" before you run the next code chunk!

```{r}
business <- readRDS(here("data", "raw_data","business.rds"))

reviews_sampled <- reviews_sampled %>%
  left_join(business %>% select(business_id, is_open), by = "business_id")
```
