```{r}
required_packages <- c("tidyverse", "data.table", "here", "googledrive")

for (pkg in required_packages) {
	if (!requireNamespace(pkg, quietly = TRUE)) {
		suppressMessages(install.packages(pkg))
	}
}
#load all the dependencies
invisible(lapply(required_packages, function(pkg) {
	suppressPackageStartupMessages(library(pkg, character.only = TRUE))
}))

```

```{r}
folder_id <- "1oRNbZpA4kXZRsvcNe5K1FRYFKqqT5W2h"	#folder id
googledrive::drive_deauth()
folder <- drive_ls(as_id(folder_id))
filename <- "reviews_sampled.rds"
file_id <- folder[folder$name==filename,] %>% pull(id) %>% as.character()
drive_download(as_id(file_id), path = here("data", "training_data",filename), overwrite = TRUE)

reviews_sampled <- readRDS(here("data", "training_data", filename))
```


```{r}
# Create a table with the variable names

variable_table <- data.frame(
  Variable = c("business_id", "review_id", "text", "stars", "date", "user_id", "is_open", "checkin", "last_checkin"),
  Description = c("The business ID of the reviewed company", "The ID of the review", "The complete review of the user", "The amount of stars (between 1-5) given by the user", "The timestamp of the review", "The ID of the user who submitted the review", "Whether the restaurant is active/open (1) or closed (0)", "All recorded checkin timestamps of reviews for a company", "The last recorded checkin timestamp of a review for a company")
)

variable_table
```
